### ISSUE TITLE
Eloquent with GlobalScope have Exception

### ISSUE THREAD

**Issue by dryyun** [damiantw/laravel-scout-mysql-driver#10] opened 2016-11-26 15:56 UTC
I have a model ``Post`` use ``GlobalScope`` 
```
    protected static function boot()
    {
        parent::boot();

       static::addGlobalScope('status', function(Builder $builder) {
            $builder->where('status', '=', 1);
        });

    }
```
And use ``laravel-scout-mysql-driver`` for search  q=``dfds``

It occur  QueryException  
``select count(*) as aggregate from `posts` where (`content` LIKE :_search0) and `posts`.`deleted_at` is null and `status` = %dfds%)``

**Comment by WellsMediaGroup** [comment] 2017-05-03 19:43
I believe the issue is the mixing of named and positional parameters.  Eloquent uses positional and this lib uses named.

If you are using the Like comparison, change

```$queryString .= "`$field` LIKE :_search$itr OR ";```
to
```$queryString .= "`$field` LIKE ? OR ";```

**Comment by ChrisThompsonTLDR** [comment] 2017-05-03 19:44
I believe the issue is the mixing of named and positional parameters.  Eloquent uses positional and this lib uses named.

If you are using the Like comparison, change

```$queryString .= "`$field` LIKE :_search$itr OR ";```
to
```$queryString .= "`$field` LIKE ? OR ";```

**Comment by c4l3b** [comment] 2017-07-07 18:56
Fixed in #31

**Closed** 2017-07-13 05:53 UTC
